---
- name: Ensure dependencies
  apt:
    name: [jq, curl, gnupg]
    state: present
    update_cache: yes

- name: Add HashiCorp APT key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install Vault
  apt:
    name: vault{{ ('='+vault_version) if vault_version|length > 0 else '' }}
    state: present
    update_cache: yes

- name: Ensure vault user and directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('vault') }}"
    group: "{{ item.group | default('vault') }}"
    mode: "{{ item.mode | default('0750') }}"
  loop:
    - { path: /opt/vault/data }
    - { path: /etc/vault.d, owner: root, group: root, mode: '0755' }

- name: Render Vault configuration
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: root
    group: vault
    mode: '0640'

- name: Enable and start Vault service
  systemd:
    name: vault
    enabled: yes
    state: started

