name: foundation-02-github-organisation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["foundation-01-remote-state"]
    types: [completed]

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      contents: read
    env:
      # DigitalOcean Spaces bucket name, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      TF_VAR_region: ${{ vars.DO_STATE_BUCKET_REGION }}
      TF_VAR_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}

      # AWS variables, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

      # GitHub organisation PAT used for , CRUD on the github organisation variables and secrets.
      TF_VAR_github_token: ${{ secrets.02_GITHUB_TOKEN_PAT }}

      # GitHub organisation variables, added when managing the github organisation through terraform in 02-github-organisation.yml
      TF_VAR_github_organisation: ${{ vars.ORGANISATION_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply GitHub organisation stack
        working-directory: terraform/02-github-organisation
        run: |
          chmod +x ./apply.sh
          ./apply.sh
