name: foundation-02-github-organization

on:
  workflow_dispatch:
  push:
    paths:
      - 'deployment/foundation/terraform/02-github-organization/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # AWS variables, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

      # GitHub organization PAT used for , CRUD on the github organization variables and secrets.
      TF_VAR_github_token: ${{ secrets.02_GITHUB_TOKEN_PAT }}

      # GitHub organization variables, added when managing the github organization through terraform in 02-github-organization.yml
      TF_VAR_github_organization: ${{ vars.ORGANIZATION_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply GitHub organization stack
        working-directory: deployment/foundation/terraform/02-github-organization
        run: |
          ./apply.sh
