name: foundation-03-github-foundation-repo

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["foundation-02-github-organisation"]
    types: [completed]

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      contents: read
    env:
      # DigitalOcean Spaces bucket name, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      TF_VAR_region: ${{ vars.DO_STATE_BUCKET_REGION }}
      TF_VAR_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}

      # AWS variables, used for access to spaces 'remote state' bucket for terraform. Added when creating the github
      # repository through terraform in 03-github-foundation-repo.yml
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

      # GitHub organization PAT used for creating the GitHub repository and adding repository variables.
      TF_VAR_github_token: ${{ secrets.REPO_CREATION_TOKEN }}

      # GitHub repository variables, added when creating the github repository through terraform in 03-github-foundation-repo.yml
      TF_VAR_repository_name: ${{ vars.REPOSITORY_NAME }}
      TF_VAR_repository_description: ${{ vars.REPOSITORY_DESCRIPTION }}
      TF_VAR_repository_visibility: ${{ vars.REPOSITORY_VISIBILITY }}
      TF_VAR_template_owner: ${{ vars.TEMPLATE_OWNER }}
      TF_VAR_template_repository: ${{ vars.TEMPLATE_REPOSITORY }}
      TF_VAR_is_template: ${{ vars.IS_TEMPLATE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply foundation repo stack
        working-directory: terraform/03-github-foundation-repo
        run: |
          chmod +x ./apply.sh
          ./apply.sh
