name: foundation-04-github-configure-org

on:
  workflow_dispatch:
  # workflow_run:
    # workflows: ["foundation-03-github-foundation-repo"]
    # types: [completed]

jobs:
  configure-organisation:
    runs-on: ubuntu-latest
    environment: production
    # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      contents: read
    env:
      # DigitalOcean Spaces bucket name, used for access to spaces 'remote state' bucket for terraform
      TF_VAR_region: ${{ vars.DO_STATE_BUCKET_REGION }}
      TF_VAR_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}

      # AWS variables, used for access to spaces 'remote state' bucket for terraform
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

      # GitHub token used for creating teams
      TF_VAR_github_token: ${{ secrets.REPO_CREATION_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Generate backend file
        working-directory: terraform/04-github-org-teams
        run: |
          # Load common helpers
          COMMON_SH="../../scripts/common.sh"
          if [[ -f "${COMMON_SH}" ]]; then
            source "${COMMON_SH}"
          else
            echo "[ERROR] Common helper not found: ${COMMON_SH}"
            exit 1
          fi
          
          # Generate backend.hcl from bucket region and name
          SHARED_BACKEND_HCL="../backend.hcl"
          generate_backend_file "${TF_VAR_region}" "${TF_VAR_bucket_name}" "${SHARED_BACKEND_HCL}"

      - name: Terraform Init
        working-directory: terraform/04-github-org-teams
        run: |
          terraform init -backend-config="../backend.hcl"

      - name: Terraform Plan
        working-directory: terraform/04-github-org-teams
        run: |
          terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform/04-github-org-teams
        run: |
          terraform apply -auto-approve tfplan
