name: foundation-05-github-configure-repo

on:
  workflow_dispatch:
  # workflow_run:
    # workflows: ["foundation-04-configure-org"]
    # types: [completed]

jobs:
  setup-production:
    runs-on: ubuntu-latest
    environment: production
    # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    permissions:
      contents: read
    env:
      # DigitalOcean Spaces bucket name, used for access to spaces 'remote state' bucket for terraform
      TF_VAR_region: ${{ vars.DO_STATE_BUCKET_REGION }}
      TF_VAR_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}

      # AWS variables, used for access to spaces 'remote state' bucket for terraform
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}

      # GitHub token used for creating branch and environment
      TF_VAR_github_token: ${{ secrets.REPO_CREATION_TOKEN }}

      # Repository variables
      TF_VAR_repository_name: ${{ vars.REPOSITORY_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply production branch and environment stack
        working-directory: terraform/04-setup-production-branch
        run: |
          chmod +x ./apply.sh
          ./apply.sh
