name: foundation-03-github-foundation-repo

on:
  workflow_dispatch:
  push:
    paths:
      - 'deployment/foundation/terraform/03-github-foundation-repo/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL_S3: https://ams3.digitaloceanspaces.com

      TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN_PAT }}
      TF_VAR_github_owner: ${{ vars.GITHUB_ORG_NAME }}
      TF_VAR_repository_name: ${{ vars.FOUNDATION_REPO_NAME || 'cloud-setup.foundation' }}
      TF_VAR_repository_visibility: ${{ vars.FOUNDATION_REPO_VISIBILITY || 'private' }}
      TF_VAR_template_owner: ${{ vars.FOUNDATION_TEMPLATE_OWNER || 'Zeepaardje98' }}
      TF_VAR_template_repository: ${{ vars.FOUNDATION_TEMPLATE_REPO || 'cloud-setup.foundation' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply foundation repo stack
        working-directory: deployment/foundation/terraform/03-github-foundation-repo
        run: |
          ./apply.sh


