name: foundation-01-remote-state

on:
  workflow_dispatch:
  push:
    paths:
      - 'deployment/foundation/terraform/01-digitalocean-remote-state/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL_S3: https://ams3.digitaloceanspaces.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply remote state stack
        working-directory: deployment/foundation/terraform/01-digitalocean-remote-state
        run: |
          ./apply.sh


